/*!
* System: Aurora Internet Banking Platform
* Class:  Nationwide.Aurora.Scripts.SitewideHeader.js
*
* Copyright (c) Nationwide Building Society 2010. All rights reserved.
*/
function initialiseLogoutWarningTimer(){secondsBeforeDisplayElement!=null&&(clearTimeout(pageTimoutWarningTimerId),pageTimoutWarningTimerId=setTimeout(displayTimeOutWarning,secondsBeforeDisplayElement.innerHTML*1e3))}function displayTimeOutWarning(){$.colorbox({inline:!0,href:"#timeoutLightbox",transition:"elastic",opacity:.5,scrolling:!1,showClose:!1,escKey:!1,overlayClose:!1,nested:!0,onClosed:function(){clearInterval(timeOutWarningCountdownTimerId);initialiseLogoutWarningTimer();inactivityWarningActive=!1}});inactivityWarningActive=!0;secondsRemainingBeforeAutoLogout=secondsToDisplayWarning;secondsLeftElement.innerHTML=secondsRemainingBeforeAutoLogout;timeOutWarningCountdownTimerId=window.setInterval(refreshLightboxCountdown,1e3)}function refreshLightboxCountdown(){secondsRemainingBeforeAutoLogout>0?(secondsLeftElement.innerHTML=(secondsRemainingBeforeAutoLogout<10?"0":"")+secondsRemainingBeforeAutoLogout,secondsRemainingBeforeAutoLogout--):(clearInterval(timeOutWarningCountdownTimerId),clearInterval(pageTimoutWarningTimerId),$(window).unbind("beforeunload"),window.location=logoutPageRoute)}function extendServerSession(){$.ajax({type:"GET",url:extendServerSessionRoute})}function blockElement(element){var loadingImageUrl;loadingImageUrl=$.viewData.loadingImage!=null&&$.viewData.loadingImage!=""?'url("'+document.location.protocol+"//"+document.location.hostname+$.viewData.loadingImage+'")':"";element.block({message:null,timeout:5e3,overlayCSS:{opacity:.5,background:"#000 "+loadingImageUrl+" no-repeat 50% 100px"},fadeIn:0})}$(function(){var revealContainer=$("#whatyoucando-reveal-container"),revealLink=$("#whatyoucando-reveal-link");revealLink.click(function(e){e.preventDefault();e.stopPropagation();revealContainer.fadeIn(200)});$("#nav-view ul li a").click(function(){$(this).parent("form").submit()})});
/*!
* System: Aurora Internet Banking Platform
* Class:  Nationwide.Aurora.Scripts.Logout.js
*
* Copyright (c) Nationwide Building Society 2010. All rights reserved.
*/
$(document).ready(function(){secondsBeforeDisplayElement=document.getElementById("secondsBeforeWarningDisplay");secondsToDisplayWarning=document.getElementById("secondsToDisplayWarning").innerHTML;logoutPageRoute=document.getElementById("logoutPageRoute").innerHTML;extendSessionRoute=document.getElementById("extendSessionRoute").innerHTML;extendServerSessionRoute=document.getElementById("extendServerSessionRoute").innerHTML;secondsLeftElement=document.getElementById("secsLeft");$("#lbBtnYesRemain").click(function(e){e.preventDefault();$.ajax({type:"GET",url:extendSessionRoute});$.colorbox.close()});initialiseLogoutWarningTimer();$(this).on("click keypress scroll touch",function(){inactivityWarningActive||initialiseLogoutWarningTimer()});var serverPingIntervalInSeconds=document.getElementById("keepServerSessionAliveIntervalInSeconds").innerHTML;setInterval(extendServerSession,serverPingIntervalInSeconds*1e3)});var secondsBeforeDisplayElement,secondsToDisplayWarning,inactivityWarningActive,secondsLeftElement,secondsRemainingBeforeAutoLogout,pageTimoutWarningTimerId,timeOutWarningCountdownTimerId,logoutPageRoute,extendSessionRoute,extendServerSessionRoute;
/*!
* System: Aurora Internet Banking Platform
* Copyright (c) Nationwide Building Society 2010. All rights reserved.
*/
$(function($){var link,form;$("#stage").roundCorners(["full-blue-container","split-bottom-content-pod","split-top-blue-content-pod","content-pod","bg-box-ff","bg-box-f7","tech-error","next-logical-step"]);$("#user-content").roundCorners(["secondary-nav","related-services","back-nav"]);var rangeButtons=$("#range-buttons"),downloadFileToolTip=$("#downloadFileTooltip"),autoDownloadCsv=$.viewData.autoDownloadCsv,autoDownloadOfx=$.viewData.autoDownloadOfx;rangeButtons.find("a").click(function(e){rangeButtons.trigger("range",[this.id])}).end().bind("range",function(e,buttonId){function format(date){return formatter(date,"dd/MM/yyyy hh:mm:ss")}var months=/\d+/.exec(buttonId||""),date=new Date,formatter=$.date.format,start=format(new Date(date.getFullYear(),date.getMonth(),1)),end=format(date);months&&months[0]&&(start=format(new Date(date.getFullYear(),date.getMonth()-months[0],1)),end=format(new Date(date.getFullYear(),date.getMonth(),date.getDate()+1,0,0,-1)));downloadFileToolTip.find("input.start").each(function(){this.value=start});downloadFileToolTip.find("input.end").each(function(){this.value=end})});downloadFileToolTip.find("a.downloadLink").click(function(e){e.preventDefault();$.bypassUnloadMsg=!0;var form=$(this).closest("form").submit()});(autoDownloadCsv||autoDownloadOfx)&&(link=autoDownloadCsv?downloadFileToolTip.find("a.downloadCsvLink"):downloadFileToolTip.find("a.downloadOfxLink"),form=link.closest("form").submit())});$.fn.extend({registerSortListener:function(){return this.each(function(){var table=$(this),settings=table.data("tablesorter");table.bind("userSortEnd",function(e){var storedSortHeader=table.find(".storedSort"),sortType;storedSortHeader.length&&(sortType=storedSortHeader.hasClass(settings.cssAsc)?$.viewData.statementSortType.descending:storedSortHeader.hasClass(settings.cssDesc)?$.viewData.statementSortType.ascending:!1,sortType!==!1&&($.viewData.userSortPreference=[[0,sortType]],$.ajax({type:"POST",dataType:"json",url:$.viewData.statementSortUrl,traditional:!0,data:{sortOrder:sortType}})))})})}})